<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "werkstattsuche"
 *
 * Auto generated by Extension Builder 2015-07-13
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'werkstattsuche',
	'description' => 'werkstattsuche fuer die LAG Berlin',
	'category' => 'plugin',
	'author' => 'Thomas Wöhlke',
	'author_email' => 'woehlke@faktura-berlin.de',
	'state' => 'stable',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '0.0.7',
	'constraints' => array(
		'depends' => array(
			'typo3' => '6.2.0-6.2.99',
			't3sbootstrap' => '2.0.3-2.1.99',
			'wec_map' => '3.1.1-3.1.99',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);